/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 06 09:51:20 GMT 2018
 */

package edu.stanford.nlp.util;

import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.ling.Label;
import edu.stanford.nlp.ling.StringLabel;
import edu.stanford.nlp.ling.Word;
import edu.stanford.nlp.ling.WordLemmaTag;
import edu.stanford.nlp.objectbank.ObjectBank;
import edu.stanford.nlp.objectbank.ReaderIteratorFactory;
import edu.stanford.nlp.process.CoreLabelTokenFactory;
import edu.stanford.nlp.process.Morphology;
import edu.stanford.nlp.sequences.SeqClassifierFlags;
import edu.stanford.nlp.stats.IntCounter;
import edu.stanford.nlp.trees.LabeledScoredTreeFactory;
import edu.stanford.nlp.trees.LabeledScoredTreeNode;
import edu.stanford.nlp.trees.SimpleTree;
import edu.stanford.nlp.trees.Tree;
import edu.stanford.nlp.util.ArrayUtils;
import edu.stanford.nlp.util.DeltaIndex;
import edu.stanford.nlp.util.Filters;
import edu.stanford.nlp.util.HashIndex;
import edu.stanford.nlp.util.MapFactory;
import edu.stanford.nlp.util.MutableInteger;
import edu.stanford.nlp.util.Pair;
import java.lang.reflect.Array;
import java.net.Proxy;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
 
public class ArrayUtils_ESTest extends ArrayUtils_ESTest_scaffolding {

	@Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Short[] shortArray0 = new Short[4];
      short short0 = (short)0;
      Short short1 = new Short((short)0);
      shortArray0[0] = short1;
      Short short2 = Short.valueOf(short0);
      shortArray0[1] = short2;
      Short short3 = new Short((short)0);
      shortArray0[2] = short3;
      Short short4 = new Short(short0);
      ArrayUtils.toPrimitive(shortArray0, (short)0);
      int[] intArray0 = new int[1];
      intArray0[0] = (int) short0;
      ArrayUtils.gapEncode(intArray0);
      Predicate<Pair> predicate0 = (Predicate<Pair>) mock(Predicate.class, new ViolatedAssumptionAnswer());
      doReturn(false, false, false, false).when(predicate0).test(nullable(edu.stanford.nlp.util.Pair.class));
      ArrayUtils.getSubListIndex((Object[]) shortArray0, (Object[]) shortArray0, predicate0);
      Long[] longArray0 = new Long[5];
      Long long0 = new Long(short0);
      longArray0[0] = long0;
      Long.getLong("");
      longArray0[1] = null;
      Long long1 = new Long(short0);
      longArray0[2] = long1;
      Long long2 = new Long((short)0);
      longArray0[3] = long2;
      Long long3 = new Long((-313L));
      Long.compareUnsigned((long) longArray0[3], 754L);
      longArray0[4] = long3;
      ArrayUtils.toPrimitive(longArray0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      // Undeclared exception!
      try { 
        ArrayUtils.gapDecodeList((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.stanford.nlp.util.ArrayUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      Object object0 = new Object();
      objectArray0[0] = object0;
      Object object1 = new Object();
      objectArray0[1] = object1;
      Object object2 = new Object();
      objectArray0[2] = object2;
      ArrayUtils.subArray(objectArray0, (-1886), 521);
      byte[] byteArray0 = new byte[6];
      byteArray0[0] = (byte)84;
      byteArray0[1] = (byte)0;
      byteArray0[2] = (byte) (-60);
      byteArray0[3] = (byte) (-103);
      byteArray0[4] = (byte)0;
      byteArray0[5] = (byte)117;
      int[] intArray0 = ArrayUtils.gapDecode(byteArray0);
      ArrayUtils.toDouble(intArray0);
      Object[] objectArray1 = new Object[6];
      Object object3 = new Object();
      objectArray1[0] = object3;
      objectArray1[1] = (Object) (byte) (-60);
      objectArray1[2] = (Object) (byte)0;
      objectArray1[3] = (Object) (byte)84;
      objectArray1[4] = object2;
      objectArray1[5] = (Object) (byte)0;
      ArrayUtils.subArray(objectArray1, (byte)0, 49);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Integer[] integerArray0 = new Integer[6];
      int int0 = 0;
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      Integer integer0 = new Integer(0);
      integerArray0[1] = integer0;
      Integer integer1 = new Integer(0);
      integerArray0[2] = integer1;
      Integer integer2 = new Integer(0);
      integerArray0[3] = integer2;
      Integer integer3 = new Integer(int0);
      integerArray0[4] = integer3;
      ArrayUtils.toPrimitive((Integer[]) null);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      Object object0 = new Object();
      objectArray0[0] = object0;
      Object object1 = new Object();
      objectArray0[1] = object1;
      Object object2 = new Object();
      objectArray0[2] = object2;
      int int0 = (-1886);
      ArrayUtils.subArray(objectArray0, (-1886), 521);
      byte[] byteArray0 = new byte[6];
      byteArray0[0] = (byte)0;
      byteArray0[1] = (byte)0;
      FileSystemHandling.appendDataToFile((EvoSuiteFile) null, byteArray0);
      byteArray0[2] = (byte) (-60);
      byteArray0[3] = (byte) (-103);
      byteArray0[4] = (byte)0;
      byteArray0[5] = (byte)117;
      ArrayUtils.gapDecode(byteArray0);
      // Undeclared exception!
      try { 
        ArrayUtils.deltaEncodeList((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.stanford.nlp.util.ArrayUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[0] = (-1589);
      intArray0[1] = (-1354);
      intArray0[2] = (-1354);
      intArray0[3] = 359;
      intArray0[4] = 1595;
      intArray0[6] = (-1354);
      intArray0[7] = 1821;
      int[] intArray1 = ArrayUtils.copy(intArray0);
      ArrayUtils.equalContents(intArray0, intArray1);
      Morphology morphology0 = new Morphology();
      ObjectBank<Double> objectBank0 = ObjectBank.getLineIterator("aNB;VMjV,Y", (Function<String, Double>) morphology0);
      // Undeclared exception!
      try { 
        ArrayUtils.asPrimitiveDoubleArray(objectBank0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.FileNotFoundException
         //
         verifyException("edu.stanford.nlp.io.IOUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Filters.ConjFilter<String> filters_ConjFilter0 = new Filters.ConjFilter<String>((List<Predicate<String>>) null);
      ArrayUtils.filter(stringArray0, (Predicate<? super String>) filters_ConjFilter0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      double[][] doubleArray0 = new double[3][0];
      double[] doubleArray1 = new double[9];
      doubleArray1[0] = 0.0;
      doubleArray1[1] = 160.3896598821;
      doubleArray1[2] = 0.0;
      doubleArray1[3] = 0.1;
      doubleArray1[4] = 0.0;
      doubleArray1[5] = 0.0;
      doubleArray1[6] = 1.0E9;
      doubleArray1[7] = 0.0;
      doubleArray1[8] = 1377.289;
      doubleArray0[0] = doubleArray1;
      double[] doubleArray2 = new double[6];
      doubleArray2[0] = 160.3896598821;
      doubleArray2[1] = 0.0;
      doubleArray2[2] = 0.1;
      doubleArray2[3] = 0.1;
      doubleArray2[4] = 1.0E9;
      doubleArray2[5] = 1377.289;
      doubleArray0[1] = doubleArray2;
      double[] doubleArray3 = new double[3];
      doubleArray3[0] = 160.3896598821;
      doubleArray3[1] = 1.0E9;
      doubleArray3[2] = 570.7986058066;
      doubleArray0[1] = doubleArray3;
      double[][] doubleArray4 = ArrayUtils.copy(doubleArray0);
      ArrayUtils.equals(doubleArray4, doubleArray4);
      ArrayUtils.equalContents((int[][]) null, (int[][]) null);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      FileSystemHandling.setPermissions((EvoSuiteFile) null, false, true, false);
      int[] intArray0 = new int[8];
      intArray0[0] = 18;
      intArray0[1] = 2380;
      intArray0[2] = 190;
      intArray0[3] = (-886);
      intArray0[4] = 730;
      intArray0[5] = 19;
      intArray0[6] = 424;
      intArray0[7] = 5;
      ArrayUtils.asList(intArray0);
      ArrayUtils.copy((double[]) null);
      double[][] doubleArray0 = new double[2][3];
      doubleArray0[0] = null;
      doubleArray0[1] = null;
      ArrayUtils.copy(doubleArray0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      List<Integer>[] listArray0 = (List<Integer>[]) Array.newInstance(List.class, 2);
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)0;
      byteArray0[1] = (byte)3;
      byteArray0[2] = (byte)0;
      List<Integer> list0 = ArrayUtils.deltaDecodeList(byteArray0);
      assertEquals(3, byteArray0.length);
      assertNotNull(list0);
      assertFalse(list0.isEmpty());
      assertEquals(20, list0.size());
      assertArrayEquals(new byte[] {(byte)0, (byte)3, (byte)0}, byteArray0);
      
      listArray0[0] = list0;
      Object[] objectArray0 = new Object[9];
      objectArray0[0] = (Object) (byte)0;
      objectArray0[1] = (Object) (byte)0;
      objectArray0[2] = (Object) (byte)0;
      objectArray0[3] = (Object) list0;
      objectArray0[4] = (Object) list0;
      objectArray0[5] = (Object) (byte)0;
      objectArray0[6] = (Object) (byte)0;
      objectArray0[7] = (Object) (byte)3;
      objectArray0[8] = (Object) list0;
      Predicate<Pair> predicate0 = (Predicate<Pair>) mock(Predicate.class, new ViolatedAssumptionAnswer());
      doReturn(false, false, false, false, false).when(predicate0).test(nullable(edu.stanford.nlp.util.Pair.class));
      List<Integer> list1 = ArrayUtils.getSubListIndex(objectArray0, objectArray0, predicate0);
      assertEquals(9, objectArray0.length);
      assertNotNull(list1);
      assertNotSame(list1, list0);
      assertFalse(list1.equals((Object)list0));
      assertEquals(0, list1.size());
      assertTrue(list1.isEmpty());
      
      listArray0[1] = list1;
      Set<List<Integer>> set0 = ArrayUtils.asImmutableSet(listArray0);
      assertEquals(2, listArray0.length);
      assertNotNull(set0);
      assertTrue(set0.contains(list0));
      assertEquals(2, set0.size());
      assertFalse(set0.isEmpty());
      
      double[][][] doubleArray0 = new double[0][9][3];
      double[][][] doubleArray1 = ArrayUtils.copy(doubleArray0);
      assertEquals(0, doubleArray0.length);
      assertEquals(0, doubleArray1.length);
      assertNotNull(doubleArray1);
      assertNotSame(doubleArray0, doubleArray1);
      assertNotSame(doubleArray1, doubleArray0);
      assertFalse(doubleArray1.equals((Object)doubleArray0));
      
      double[][] doubleArray2 = new double[0][7];
      ArrayUtils.equals(doubleArray2, (double[][]) null);
      Random.setNextRandom((byte)0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      double[][] doubleArray0 = new double[3][5];
      double[] doubleArray1 = new double[2];
      doubleArray1[0] = 313.0108973675;
      doubleArray1[1] = (-1.0);
      doubleArray0[0] = doubleArray1;
      double[] doubleArray2 = new double[3];
      doubleArray2[0] = 0.0;
      doubleArray2[1] = (-2667.12);
      doubleArray2[2] = (-1.0);
      doubleArray0[1] = doubleArray2;
      double[] doubleArray3 = new double[8];
      doubleArray3[0] = 313.0108973675;
      doubleArray3[1] = (-1.0);
      doubleArray3[2] = (-2667.12);
      doubleArray3[3] = (-1.0);
      doubleArray3[4] = 313.0108973675;
      doubleArray3[5] = (-1.0);
      doubleArray3[6] = (-1.0);
      doubleArray3[7] = 0.0;
      doubleArray0[2] = doubleArray3;
      ArrayUtils.fill(doubleArray0, (-1.0));
      Integer[] integerArray0 = new Integer[4];
      int int0 = 20;
      Integer integer0 = new Integer(20);
      integerArray0[0] = integer0;
      Integer integer1 = Integer.getInteger("", (-1393));
      integerArray0[1] = integer1;
      Integer integer2 = Integer.getInteger("", (-1589));
      integerArray0[2] = integer2;
      Integer integer3 = new Integer(int0);
      integerArray0[3] = integer3;
      Integer[] integerArray1 = new Integer[3];
      integerArray1[0] = integer1;
      integerArray1[1] = integer0;
      integerArray1[2] = integer3;
      ArrayUtils.compareArrays(integerArray0, integerArray1);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      double[][] doubleArray0 = new double[0][7];
      ArrayUtils.toString(doubleArray0);
      Integer[] integerArray0 = new Integer[5];
      Integer integer0 = new Integer((-800));
      integerArray0[0] = integer0;
      integerArray0[1] = integerArray0[0];
      Integer integer1 = new Integer((int) integerArray0[0]);
      integerArray0[2] = integer1;
      Integer integer2 = new Integer(1714);
      integerArray0[3] = integer2;
      Integer integer3 = new Integer((int) integerArray0[3]);
      integerArray0[4] = integer3;
      int[] intArray0 = ArrayUtils.toPrimitive(integerArray0);
      ArrayUtils.gapEncodeList(intArray0);
      float[] floatArray0 = new float[7];
      floatArray0[0] = (float) (int)integerArray0[1];
      floatArray0[1] = (float) (int)integerArray0[3];
      floatArray0[2] = (float) (int)integerArray0[2];
      floatArray0[3] = (float) (int)integerArray0[1];
      floatArray0[4] = (float) (int)integerArray0[1];
      floatArray0[5] = (float) (int)integerArray0[3];
      floatArray0[6] = (float) (int)integerArray0[3];
      ArrayUtils.toDouble(floatArray0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      Object object0 = new Object();
      objectArray0[0] = object0;
      Object object1 = new Object();
      objectArray0[1] = object1;
      Object object2 = new Object();
      objectArray0[2] = object2;
      ArrayUtils.subArray(objectArray0, (-1886), 521);
      byte[] byteArray0 = new byte[6];
      byteArray0[0] = (byte)95;
      byteArray0[1] = (byte)0;
      byteArray0[4] = (byte)0;
      byteArray0[5] = (byte)117;
      int[] intArray0 = ArrayUtils.gapDecode(byteArray0);
      ArrayUtils.toDouble(intArray0);
      Object[] objectArray1 = new Object[7];
      objectArray1[0] = (Object) (byte)95;
      objectArray1[1] = object2;
      objectArray1[2] = (Object) (byte)95;
      Object object3 = new Object();
      objectArray1[3] = object3;
      objectArray1[4] = (Object) (byte)95;
      objectArray1[5] = object1;
      objectArray1[6] = (Object) (byte)95;
      Predicate<Pair> predicate0 = (Predicate<Pair>) mock(Predicate.class, new ViolatedAssumptionAnswer());
      ArrayUtils.getSubListIndex(objectArray1, objectArray0, predicate0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      IntCounter<Integer> intCounter0 = new IntCounter<Integer>();
      Set<Integer> set0 = intCounter0.keysAt(1147);
      HashIndex<Integer> hashIndex0 = new HashIndex<Integer>(set0);
      DeltaIndex<Integer> deltaIndex0 = new DeltaIndex<Integer>(hashIndex0, hashIndex0);
      int[] intArray0 = ArrayUtils.asPrimitiveIntArray(deltaIndex0);
      ArrayUtils.gapEncodeList(intArray0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      double[] doubleArray0 = new double[0];
      ArrayUtils.copy(doubleArray0);
      Object[] objectArray0 = new Object[8];
      Object object0 = new Object();
      objectArray0[0] = object0;
      Object object1 = new Object();
      objectArray0[1] = object1;
      Object object2 = new Object();
      objectArray0[2] = object2;
      Object object3 = new Object();
      objectArray0[3] = object3;
      Object object4 = new Object();
      objectArray0[4] = object4;
      Object object5 = new Object();
      objectArray0[5] = object5;
      Object object6 = new Object();
      objectArray0[6] = object6;
      Object object7 = new Object();
      objectArray0[7] = object7;
      // Undeclared exception!
      try { 
        ArrayUtils.subArray(objectArray0, (-2611), (-1216));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      double[][] doubleArray0 = new double[8][6];
      double[] doubleArray1 = new double[3];
      doubleArray1[0] = (-1029.528147324076);
      doubleArray1[1] = 2232.935;
      doubleArray1[2] = (-2554.475248688851);
      doubleArray0[0] = doubleArray1;
      double[] doubleArray2 = new double[6];
      doubleArray2[0] = 2232.935;
      doubleArray2[1] = (-1029.528147324076);
      doubleArray2[2] = (-2554.475248688851);
      doubleArray2[3] = 2232.935;
      doubleArray2[4] = (-1029.528147324076);
      doubleArray2[5] = (-2554.475248688851);
      doubleArray0[1] = doubleArray2;
      double[] doubleArray3 = new double[5];
      doubleArray3[0] = 2232.935;
      doubleArray3[1] = 20.0;
      doubleArray3[2] = (-2554.475248688851);
      doubleArray3[3] = 1196.85154234;
      doubleArray3[4] = 2232.935;
      doubleArray0[2] = doubleArray3;
      double[] doubleArray4 = new double[6];
      doubleArray4[0] = 20.0;
      doubleArray4[1] = (-1029.528147324076);
      doubleArray4[2] = (-1029.528147324076);
      doubleArray4[3] = 2232.935;
      doubleArray4[4] = 1196.85154234;
      doubleArray4[5] = 20.0;
      doubleArray0[3] = doubleArray4;
      double[] doubleArray5 = new double[9];
      doubleArray5[0] = 1196.85154234;
      doubleArray5[1] = 20.0;
      doubleArray5[2] = (-2554.475248688851);
      doubleArray5[3] = 1196.85154234;
      doubleArray5[4] = 1196.85154234;
      doubleArray5[5] = 3.0E9;
      doubleArray5[6] = 20.0;
      doubleArray5[7] = 0.0;
      doubleArray5[8] = (-2554.475248688851);
      doubleArray0[4] = doubleArray5;
      double[] doubleArray6 = new double[8];
      doubleArray6[0] = 2232.935;
      doubleArray6[1] = (-2554.475248688851);
      doubleArray6[2] = (-2554.475248688851);
      doubleArray6[3] = 0.0;
      doubleArray6[4] = 2232.935;
      doubleArray6[5] = 2232.935;
      doubleArray6[6] = 2232.935;
      doubleArray6[7] = (-1029.528147324076);
      doubleArray0[5] = doubleArray6;
      double[] doubleArray7 = new double[4];
      doubleArray7[0] = (-2554.475248688851);
      doubleArray7[1] = (-1029.528147324076);
      doubleArray7[2] = 2232.935;
      doubleArray7[3] = 3.0E9;
      doubleArray0[6] = doubleArray7;
      double[] doubleArray8 = new double[3];
      doubleArray8[0] = 0.0;
      doubleArray8[1] = 0.0;
      doubleArray8[2] = 3.0E9;
      doubleArray0[7] = doubleArray8;
      double[][] doubleArray9 = new double[0][1];
      ArrayUtils.equals(doubleArray0, doubleArray9);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      ArrayUtils.toPrimitive((Integer[]) null, 930);
      boolean[][] booleanArray0 = new boolean[6][6];
      boolean[] booleanArray1 = new boolean[0];
      booleanArray0[0] = booleanArray1;
      boolean[] booleanArray2 = new boolean[5];
      booleanArray2[0] = false;
      booleanArray2[1] = true;
      booleanArray2[2] = true;
      booleanArray2[3] = true;
      booleanArray2[4] = true;
      booleanArray0[1] = booleanArray2;
      boolean[] booleanArray3 = new boolean[7];
      booleanArray3[0] = true;
      booleanArray3[1] = true;
      booleanArray3[2] = false;
      booleanArray3[3] = true;
      booleanArray3[4] = true;
      booleanArray3[5] = true;
      booleanArray3[6] = false;
      booleanArray0[2] = booleanArray3;
      boolean[] booleanArray4 = new boolean[6];
      booleanArray4[0] = true;
      booleanArray4[1] = false;
      booleanArray4[2] = false;
      booleanArray4[3] = true;
      booleanArray4[4] = true;
      booleanArray4[5] = true;
      booleanArray0[3] = booleanArray4;
      boolean[] booleanArray5 = new boolean[7];
      booleanArray5[0] = true;
      booleanArray5[1] = false;
      booleanArray5[2] = true;
      booleanArray5[3] = true;
      booleanArray5[4] = true;
      booleanArray5[5] = true;
      booleanArray5[6] = true;
      booleanArray0[4] = booleanArray5;
      boolean[] booleanArray6 = new boolean[6];
      booleanArray6[0] = true;
      booleanArray6[1] = true;
      booleanArray6[2] = true;
      booleanArray6[3] = true;
      booleanArray6[4] = true;
      booleanArray6[5] = true;
      booleanArray0[5] = booleanArray6;
      ArrayUtils.toString(booleanArray0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      ArrayUtils.toPrimitive((Character[]) null, 'x');
      Double[] doubleArray0 = new Double[6];
      Double double0 = new Double((-1.0));
      doubleArray0[0] = double0;
      Double double1 = new Double(3194.559147974731);
      doubleArray0[1] = double1;
      Double double2 = new Double((double) doubleArray0[0]);
      doubleArray0[2] = double2;
      Double double3 = new Double((-1007.337801911));
      doubleArray0[3] = double3;
      Double double4 = new Double(1.0);
      doubleArray0[5] = double1;
      ArrayUtils.toPrimitive(doubleArray0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[0] = 1223;
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      int int0 = (-2201);
      intArray0[1] = (-2201);
      intArray0[2] = 782;
      int int1 = (-1);
      intArray0[3] = (-1);
      intArray0[4] = (-4304);
      ArrayUtils.equalContents(intArray0, intArray0);
      double[][] doubleArrayArray0 = null;
      // Undeclared exception!
      try { 
        ArrayUtils.toString((double[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.stanford.nlp.util.ArrayUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Object[] objectArray0 = new Object[8];
      Object object0 = new Object();
      objectArray0[0] = object0;
      Object object1 = new Object();
      objectArray0[1] = object1;
      Object object2 = new Object();
      objectArray0[2] = object2;
      Object object3 = new Object();
      objectArray0[3] = object3;
      Object object4 = new Object();
      objectArray0[4] = object4;
      Object object5 = new Object();
      objectArray0[5] = object5;
      Object object6 = new Object();
      objectArray0[6] = object6;
      Object object7 = new Object();
      objectArray0[7] = object7;
      ArrayUtils.removeAt(objectArray0, (-659));
      int[] intArray0 = new int[2];
      intArray0[0] = (-659);
      intArray0[1] = (-659);
      List<Integer> list0 = ArrayUtils.asList(intArray0);
      ArrayUtils.asPrimitiveIntArray(list0);
      Long[] longArray0 = new Long[7];
      Long long0 = new Long((-659));
      longArray0[0] = long0;
      Long long1 = Long.valueOf(1L);
      longArray0[1] = long1;
      Long.getLong("");
      longArray0[2] = null;
      Long long2 = new Long(1L);
      longArray0[3] = long2;
      Long long3 = new Long((long) longArray0[0]);
      longArray0[4] = long3;
      Long long4 = new Long((-659));
      longArray0[5] = long4;
      Long long5 = new Long((-1196L));
      longArray0[6] = long5;
      ArrayUtils.toPrimitive(longArray0, 2858L);
  }
}
